### ISSUE TITLE
Failed to load baseballipsum

### ISSUE THREAD

**Issue by turtlepod** [dkotter/guten-ipsum#1]
I got this in console.

> Failed to load http://baseballipsum.apphb.com/api/?paras=5: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://wp.test' is therefore not allowed access.

Probably my local setup.

**Comment by turtlepod** [comment]
Also failed to load baseballipsum and ponnyipsum on HTTPS:

> Mixed Content: The page at 'https://wp.test/wp-admin/post.php?post=4&action=edit' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://baseballipsum.apphb.com/api/?paras=5'. This request has been blocked; the content must be served over HTTPS.

**Comment by dkotter** [comment]
Yeah, I've had multiple issues with these additional lorem ipsum services. I added them in more as a learning experience, but just removed those here: https://github.com/dkotter/guten-ipsum/commit/a39842216c21eab9b52e4ca47aff4c6edddd62af

**Comment by turtlepod** [comment]
Seem to be working well without, I think it's a cool idea. too bad some of the services do not have HTTPS.

Thank you.
