### ISSUE TITLE
Fatal Error (actually kill my site)

### ISSUE THREAD

**Issue by turtlepod** [dkotter/guten-ipsum#2]
Got white screen when activating without gutenberg installed/active.

> Fatal error: Call to undefined function register_block_type() in wp-content/plugins/guten-ipsum/guten-ipsum.php on line 24

**Comment by dkotter** [comment]
Ah, nice catch. Just pushed a fix for this (https://github.com/dkotter/guten-ipsum/commit/691e63e740c6db43a2a8c487814a64f6de683a09) that will output an error message in the admin, letting you know Gutenberg needs to be installed/activated, and stops the rest of the execution, so no fatals happen.

**Comment by turtlepod** [comment]
Awesome! thank you.
